// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace RentProof.IOS
{
	public partial class MainScreen : UIViewController
	{
		public MainScreen (IntPtr handle) : base (handle)
		{
		}
	}
}
