// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace TCheck.iOS
{
	public partial class RootViewController : UITableViewController
	{
		public RootViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
